#coding: utf-8

# Rules for initial filling standard_rules and truly_rules in VocabularyEntry. See application.rake.
defaults: &defaults
  bayes:
    regexp:
      Уфа: "(Уф+[[:word:]]+|УФ+[[:word:]]+|уфим+[[:word:]]+|Салав+[[:word:]]+[ ]+Юла+[[:word:]]+)"
      Стерлитамак: "(Стерлит+[[:word:]]+|СТЕРЛИТ+[[:word:]]+|стерлит+[[:word:]]+)"
      Салават: "(Салав+[[:word:]]+|САЛАВ+[[:word:]]+|салав+[[:word:]]+)"
      Ишимбай: "(Ишим+[[:word:]]+|ИШИМ+[[:word:]]+|ишим+[[:word:]]+)"
      Нефтекамск: "(Нефтек+[[:word:]]+|НЕФТЕК+[[:word:]]+|нефтек+[[:word:]]+)"
      domain: "Domain:.+"
      downcased:
        Уфа: "(уфим+[[:word:]]+)"
        Стерлитамак: "(стерлит+[[:word:]]+)"
        Салават: "(салав+[[:word:]]+)"
        Ишимбай: "(ишим+[[:word:]]+)"
        Нефтекамск: "(нефтек+[[:word:]]+)"
      truly_cities:
        Уфа: "(Уф+[[:word:]]+|УФ+[[:word:]]+|уфим+[[:word:]]+)"
        Стерлитамак: "(Стерлит+[[:word:]]+|СТЕРЛИТ+[[:word:]]+|стерлит+[[:word:]]+)"
        Салават: "(Салав+[[:word:]]+|САЛАВ+[[:word:]]+|салав+[[:word:]]+)"
        Ишимбай: "(Ишим+[[:word:]]+|ИШИМ+[[:word:]]+|ишим+[[:word:]]+)"
        Нефтекамск: "(Нефтек+[[:word:]]+|НЕФТЕК+[[:word:]]+|нефтек+[[:word:]]+)"



development:
  <<: *defaults
  neat_setting: 800

test:
  <<: *defaults

production:
  <<: *defaults