#coding: utf-8
defaults: &defaults
  bayes:
    klasses: ["Уфа", "Стерлитамак", "Салават", "Ишимбай", "Нефтекамск"]
    shorten_klasses: ["ufa", "str", "slv", "ish", "neft"]
    regexp:
      Уфа: "(Уф+[[:word:]]+|УФ+[[:word:]]+|уфим+[[:word:]]+|Салав+[[:word:]]+[ ]+Юла+[[:word:]]+)"
      Стерлитамак: "(Стерлит+[[:word:]]+|СТЕРЛИТ+[[:word:]]+|стерлит+[[:word:]]+)"
      Салават: "(Салав+[[:word:]]+|САЛАВ+[[:word:]]+|салав+[[:word:]]+)"
      Ишимбай: "(Ишим+[[:word:]]+|ИШИМ+[[:word:]]+|ишим+[[:word:]]+)"
      Нефтекамск: "(Нефтек+[[:word:]]+|НЕФТЕК+[[:word:]]+|нефтек+[[:word:]]+)"
      domain: "Domain:.+"


development:
  <<: *defaults
  neat_setting: 800

test:
  <<: *defaults

production:
  <<: *defaults