#coding: utf-8
defaults: &defaults
  bayes:
    klasses: ["Уфа", "Стерлитамак", "Салават", "Ишимбай", "Нефтекамск"]
    shorten_klasses: ["ufa", "str", "slv", "ish", "neft"]
    regexp:
      ufa: [ "(Уф+[[:word:]]+|УФ+[[:word:]]+|уфи+[[:word:]]+|Салав+[[:word:]]+[ ]+Юла+[[:word:]]+)", "Уфа" ]
      str: [ "(Стерлит+[[:word:]]+|СТЕРЛИТ+[[:word:]]+|стерлит+[[:word:]]+)", "Стерлитамак" ]
      slv: [ "(Салав+[[:word:]]+|САЛАВ+[[:word:]]+|салав+[[:word:]]+)", "Салават" ]
      ish: [ "(Ишим+[[:word:]]+|ИШИМ+[[:word:]]+|ишим+[[:word:]]+)", "Ишимбай" ]
      neft: [ "(Нефтек+[[:word:]]+|НЕФТЕК+[[:word:]]+|нефтек+[[:word:]]+)", "Нефтекамск" ]
      domain: [ "Domain:.+", "Domain" ]
      Уфа: "(Уф+[[:word:]]+|УФ+[[:word:]]+|уфи+[[:word:]]+|Салав+[[:word:]]+[ ]+Юла+[[:word:]]+)"
      Стерлитамак: "(Стерлит+[[:word:]]+|СТЕРЛИТ+[[:word:]]+|стерлит+[[:word:]]+)"
      Салават: "(Салав+[[:word:]]+|САЛАВ+[[:word:]]+|салав+[[:word:]]+)"
      Ишимбай: "(Ишим+[[:word:]]+|ИШИМ+[[:word:]]+|ишим+[[:word:]]+)"
      Нефтекамск: "(Нефтек+[[:word:]]+|НЕФТЕК+[[:word:]]+|нефтек+[[:word:]]+)"


development:
  <<: *defaults
  neat_setting: 800

test:
  <<: *defaults

production:
  <<: *defaults