#coding: utf-8
#
#
# CityNews - news aggregator software
# Copyright (C) 2013  Idris Yusupov
#
# This file is part of CityNews.
#
# CityNews is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# CityNews is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with CityNews.  If not, see <http://www.gnu.org/licenses/>.
#


# Rules for initial filling standard_rules and truly_rules in VocabularyEntry. See application.rake.
defaults: &defaults
  bayes:
    regexp:
      Уфа: "(Уф+[[:word:]]+|УФ+[[:word:]]+|уфим+[[:word:]]+|Салав+[[:word:]]+[ ]+Юла+[[:word:]]+)"
      Стерлитамак: "(Стерлит+[[:word:]]+|СТЕРЛИТ+[[:word:]]+|стерлит+[[:word:]]+)"
      Салават: "(Салав+[[:word:]]+|САЛАВ+[[:word:]]+|салав+[[:word:]]+)"
      Ишимбай: "(Ишим+[[:word:]]+|ИШИМ+[[:word:]]+|ишим+[[:word:]]+)"
      Нефтекамск: "(Нефтек+[[:word:]]+|НЕФТЕК+[[:word:]]+|нефтек+[[:word:]]+)"
      domain: "Domain:.+"
      downcased:
        Уфа: "(уфим+[[:word:]]+)"
        Стерлитамак: "(стерлит+[[:word:]]+)"
        Салават: "(салав+[[:word:]]+)"
        Ишимбай: "(ишим+[[:word:]]+)"
        Нефтекамск: "(нефтек+[[:word:]]+)"
      truly_cities:
        Уфа: "(Уф+[[:word:]]+|УФ+[[:word:]]+|уфим+[[:word:]]+)"
        Стерлитамак: "(Стерлит+[[:word:]]+|СТЕРЛИТ+[[:word:]]+|стерлит+[[:word:]]+)"
        Салават: "(Салав+[[:word:]]+|САЛАВ+[[:word:]]+|салав+[[:word:]]+)"
        Ишимбай: "(Ишим+[[:word:]]+|ИШИМ+[[:word:]]+|ишим+[[:word:]]+)"
        Нефтекамск: "(Нефтек+[[:word:]]+|НЕФТЕК+[[:word:]]+|нефтек+[[:word:]]+)"



development:
  <<: *defaults
  neat_setting: 800

test:
  <<: *defaults

production:
  <<: *defaults